version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/stockexchange?sslmode=disable
    depends_on:
      - db
      - tempo

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stockexchange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    image: migrate/migrate
    volumes:
      - ./internal/repository/migrations:/migrations
    command: ["-path=/migrations", "-database", "postgres://postgres:postgres@db:5432/stockexchange?sslmode=disable", "up"]
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "4317:4317" # OTLP gRPC
      - "3200:3200" # Tempo API

volumes:
  postgres_data:
