version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/stockexchange?sslmode=disable
      - EXECUTOR_CAPACITY=1024
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
    depends_on:
      - db
      - tempo

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stockexchange
    ports:
      - "5432:5432"
    volumes:
      - ./.volume/postgresql:/var/lib/postgresql/data
  # TODO save the database defore down

  migration:
    image: migrate/migrate
    volumes:
      - ./internal/repository/migrations:/migrations
    #command: ["-path=/migrations", "-database", "postgres://postgres:postgres@db:5432/stockexchange?sslmode=disable", "up"]
    entrypoint: sh -c "until nc -z db 5432; do echo waiting for db...; sleep 2; done; migrate -path=/migrations -database 'postgres://postgres:postgres@db:5432/stockexchange?sslmode=disable' up"
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.volume/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    user: "0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./.volume/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./.volume/grafana:/var/lib/grafana 
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.volume/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "3200:3200" # Tempo API

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./.volume/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

